apiVersion: v1
kind: Service
metadata:
  name: traefik-headless
  namespace: traefik-v2
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: traefik-traefik-v2
    app.kubernetes.io/name: traefik
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

