- name: Install base packages
  become: yes
  package:
    name:
      - vim
      - zsh
      - git
      - rsync
      - wget
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: yes
- name: Provision keyring
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
- name: Check for docker signing key
  shell:
    cmd: 'ls /etc/apt/keyrings/'
  register: signing_key_check
  changed_when: "not 'docker.gpg' in signing_key_check.stdout"
- name: Add apt signing key for docker repo
  become: yes
  shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes'
  when: "not 'docker.gpg' in signing_key_check.stdout"
- name: Add docker repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_facts['lsb']['codename'] }} stable
    state: present
    filename: docker
