- name: Update indexes
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
- name: Install GNS3 requirements
  become: yes
  package:
    name:
      - python3-pip
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - python3-pyqt5.qtwebsockets
      - qemu
      - qemu-kvm
      - qemu-utils
      - libvirt-clients
      - libvirt-daemon-system
      - virtinst
      - wireshark
      - xtightvncviewer
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - git
      - make
      - pcaputils
      - libpcap-dev
    state: latest
- name: Check ubridge installation
  shell:
    cmd: ls /usr/local/bin
  register: ubridge_check_result
  changed_when: "not 'ubridge' in ubridge_check_result.stdout"
- name: Clone ubridge
  become: yes
  git:
    repo: https://github.com/GNS3/ubridge.git
    dest: /opt/ubridge
    clone: yes
  when: "not 'ubridge' in ubridge_check_result.stdout"
- name: Install ubridge
  become: yes
  shell:
    cmd: 'make install'
    chdir: /opt/ubridge
  when: "not 'ubridge' in ubridge_check_result.stdout"
- name: Install GNS3
  become: yes
  pip:
    name:
      - gns3-server
- name: Copy config to server
  become: yes
  copy:
    src: /etc/ansible/res/gns_server/GNS3.conf
    dest: /etc/xdg/GNS3.conf
- name: Copy GNS3 service to server
  become: yes
  copy:
    src: /etc/ansible/res/gns_server/gns3.service
    dest: /lib/systemd/system/gns3.service
- name: Create GNS3 user
  become: yes
  user:
    name: gns3
    shell: /usr/sbin/nologin
    groups: kvm,libvirt,docker
- name: Start systemd service
  become: yes
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: gns3.service
