---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
type: kubernetes.io/basic-auth
stringData:
  username: "nextcloud" # required field for kubernetes.io/basic-auth
  password: "SecretCloudyStuff1!" # required field for kubernetes.io/basic-auth
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: longhorn-persist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud
    service: media
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextcloud
        service: media
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nextcloud
      - name: nfs
        persistentVolumeClaim:
          claimName: nextcloud-claim
      containers:
      - image: nextcloud
        name: nextcloud
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/var/www/html"
        - name: nfs
          mountPath: "/data"
        env:
          - name: domain
            value: "cloud.us.gonnella.dev"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: password
          - name: POSTGRES_DB
            value: "nextcloud"
          - name: POSTGRES_HOST
            value: "postgres.default.svc.cluster.local"
          - name: NEXTCLOUD_DATA_DIR
            value: "/data"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud
    service: media-frontend
  name: nextcloud
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
  selector:
    app: nextcloud
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
spec:
  #tls:
  # - hosts:
  #   - "*.us.gonnella.dev"
  #   secretName: letsencrypt
  rules:
    - host: cloud.us.gonnella.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nextcloud
              port:
                number: 80
