---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-persist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: qbittorrent
    service: media
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qbittorrent
        service: media
    spec:
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-claim
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent
      containers:
      - image: linuxserver/qbittorrent
        name: qbittorrent
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: downloads
          mountPath: "/downloads"
          subPath: "torrent"
      dnsConfig:
        options:
        - name: ndots
          value: "1"
        - name: single-request-reopen
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: qbittorrent
  name: qbittorrent
spec:
  ports:
  - name: web
    protocol: TCP
    port: 8080
  selector:
    app: qbittorrent
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
spec:
  rules:
  - host: torrent.k8s.bnet.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              name: web
