apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels:
    name: configs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.81.10.3
    path: "/srv/nfs/storage/configs"
