apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: configs
