apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.10.2
    path: "/mnt/animepool/nextcloud"
