apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-anime
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.10.2
    path: "/mnt/animepool/Videos/Anime"
