kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "20"
  fromBackup: ""
  diskSelector: "default"
  dataPathOverride: "/mnt/longhorn"
