#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: longhorn
#  namespace: longhorn-system
#provisioner: driver.longhorn.io
#allowVolumeExpansion: true
#parameters:
#  numberOfReplicas: "2"
#  staleReplicaTimeout: "20"
#  fromBackup: ""
#  diskSelector: "default"
#  dataPathOverride: "/mnt/longhorn"
#reclaimPolicy: Retain


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-persist
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
#  mkfsParams: ""
#  migratable: false
#  encrypted: false
#  dataLocality: "disabled"
#  replicatAutoBalance: "ignored"
#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
#  recurringJobSelector: '[{"name":"snap-group", "isGroup":true},
#                          {"name":"backup", "isGroup":false}]'
#  backingImageName: ""
#  backingImageChecksum: ""
#  backingImageDataSourceType: ""
#  backingImageDataSourceParameters: ""
#  unmapMarkSnapChainRemoved: "ignored"
#  disableRevisionCounter: false
#  replicaSoftAntiAffinity: "ignored"
#  replicaZoneSoftAntiAffinity: "ignored"
#  nfsOptions: "soft,timeo=150,retrans=3"
#  backendStoreDriver: ""
